Controllers/AuthorController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Lib2.Models;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration.UserSecrets;
using System;
using System.IO;

namespace Lib2.Controllers;

public class AuthorController : Controller
{
    private readonly LibraryContext _context;
    public AuthorController(LibraryContext context)
    {
        _context = context;
    }
    
    [HttpGet]
    public IActionResult SearchAuthor()
    {
        return View();
    }

    [HttpPost]
    public IActionResult ViewAuthor([FromForm]string searchName)
    {
        var author = _context.Authors.FirstOrDefault(a => a.Name == searchName);
        string content = System.IO.File.ReadAllText(author.Path);
        ViewBag.txtcontent = content;
        return View(author);
    }

    // Hiển thị form sửa tác giả
    // [HttpGet]
    // public IActionResult EditAuthor()
    // {
    //     return View();
    // }

    // [HttpPost]
    // public IActionResult EditAuthor([FromForm]int authorId,[FromForm]string content)
    // {
    //     var author = _context.Authors.FirstOrDefault(a => a.Id == authorId);
    //     var path = author.Path;
    //     if(System.IO.File.Exists(path))
    //     {
    //         string txt = System.IO.File.ReadAllText(path);
    //         txt = content;
    //         System.IO.File.WriteAllText(path, txt);
    //         return RedirectToAction("Index", "Home");
    //     }
    //     else{
    //         return BadRequest("Author Describe Not Found");
    //     }
    // }
    [HttpPost]
    public IActionResult EditAuthor([FromForm]int authorId)
    {
        var userId = HttpContext.Session.GetInt32("UserId");
        var isLibrarian = HttpContext.Session.GetInt32("isLibrarian");
        if(userId == null)
        {
            return RedirectToAction("Login", "Resigter");
        }
        if(isLibrarian == 0)
        {
            return BadRequest("You're not Librarian => No access");
        }
        var author = _context.Authors.FirstOrDefault(b => b.Id == authorId);
        if(author == null)
        {
            return BadRequest("Author Not Found.");
        }
        ViewBag.Id = authorId;
        return View();
    }

    [HttpPost]
    public IActionResult ChangeName([FromForm]int id, [FromForm]string name)
    {
        var userId = HttpContext.Session.GetInt32("UserId");
        if(userId == null)
        {
            return RedirectToAction("Login", "Resigter");
        }
        else{
            var author = _context.Authors.FirstOrDefault(u => u.Id == id);
            author.Name = name;
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
    [HttpPost]
    public IActionResult ChangeBirthdate([FromForm]int id, [FromForm]DateTime birthdate)
    {
        var userId = HttpContext.Session.GetInt32("UserId");
        if(userId == null)
        {
            return RedirectToAction("Login", "Resigter");
        }
        else{
            var author = _context.Authors.FirstOrDefault(u => u.Id == id);
            author.Birthdate = birthdate;
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
    [HttpPost]
    public IActionResult ChangeDescribe([FromForm]int id, [FromForm]string describe)
    {
        var userId = HttpContext.Session.GetInt32("UserId");
        if(userId == null)
        {
            return RedirectToAction("Login", "Resigter");
        }
        else{
            var author = _context.Authors.FirstOrDefault(u => u.Id == id);
            var path = author.Path;
            if(System.IO.File.Exists(path))
            {
                string txt = System.IO.File.ReadAllText(path);
                txt = describe;
                System.IO.File.WriteAllText(path, txt);
            }
            else{
                return BadRequest("Author Describe Not Found");
            }
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }

    [HttpGet]
    public IActionResult ViewAllAuthor()
    {
        var userId = HttpContext.Session.GetInt32("UserId");
        var isLibrarian = HttpContext.Session.GetInt32("isLibrarian");
        if(isLibrarian == 0)
        {
            return BadRequest("You're not Librarian => No Access");
        }
        if(userId == null)
        {
            return RedirectToAction("Login", "Resigter");
        }
        var authors = _context.Authors.ToList();
        return View(authors);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lib2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lib2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lib2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notification" asp-action="Index">Notification</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">SearchBook</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="SearchAuthor">SearchAuthor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loan" asp-action="Index">Borrow Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Profile">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="ViewFavoriteBook">Favorite</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Librarian">Librarian</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Resigter" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Resigter" asp-action="LogOut">LogOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Lib2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>